; PlatformIO Project Configuration File
; ESP32 差速小车 — 使用国内镜像加速下载

[platformio]
; 国内镜像：registry.npmmirror.com（淘宝 NPM 镜像）
registry_mirror = https://registry.npmmirror.com

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
